### ISSUE TITLE
Некоторая так называемая проблема с Антонами

### ISSUE THREAD

**Issue by maxguuse** [ksamorodov/DickName#16]
При вводе так называемого НИКНЕЙМА `Антон`, в соответствии с предоставленным вами исходного КОДА должно быть выведено слово `ГОНДОН`, однако выводится неожиданное `Хуянтон`, прошу вас исправить данную ошибку в кратчайшие сроки.

**Comment by ksamorodov** [comment]
Это не так, данная проблема была пофикшена уже давно, а разработчик допустивший это уволен и на всякий случай отшлепан по жопе
